index:
    path: /
    controller: App\Controller\TestController::helloAction

hello:
    path: /hello
    controller: App\Controller\TestController::helloAction

test:
    path: /binary-file
    controller: App\Controller\TestController::binaryFileAction
